apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: demo
      image: bsrk236/test:latest
      envFrom:
      - configMapRef:
          name: game-demo
